# Generated by Django 5.0.6 on 2025-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_votes_user_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Engineer', 'Engineer'), ('Team Leader', 'Team Leader'), ('Department Leader', 'Department Leader'), ('Senior Manager', 'Senior Manager'), ('Admin', 'Admin')], default='Unassigned', max_length=20),
        ),
    ]
