# Generated by Django 5.0.6 on 2025-04-26 18:54

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_team_name_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='department', chained_model_field='department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team'),
        ),
    ]
