# Generated by Django 5.2 on 2025-05-06 14:07

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='You must select a department before you can choose a team.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Engineer', 'Engineer'), ('Team Leader', 'Team Leader'), ('Department Leader', 'Department Leader'), ('Senior Manager', 'Senior Manager'), ('Admin', 'Admin')], default='Unassigned', help_text="Select the user's role in the organization.", max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='department', chained_model_field='department', help_text='Only teams from the selected department will appear here. Select a department first.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team'),
        ),
    ]
